


### Select lotto
GET https://mos2022.herokuapp.com/api/v2/lotto?keyword= HTTP/1.1

### Create Lotto
POST https://mos2022.herokuapp.com/api/v2/lottoadd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDU5NTMzMDAsImlkIjo1LCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYXJ0NTU1In0.0_NbqWD8JQqkZ8NG2y0TkclKMRLbD8wadLWXxgJxJPo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="id";

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

น้องทราย
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="number_lotto";

321
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="multiply";

6
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

500
------WebKitFormBoundary7MA4YWxkTrZu0gW--

