### Register 
POST https://mos2022.herokuapp.com/api/v2/register HTTP/1.1
Content-Type: application/json

{
    "name": "testse5",
    "surname": "teste4s5",
    "username": "art555",
    "password" : "1234"
}

### Login 
POST https://mos2022.herokuapp.com/api/v2/login HTTP/1.1
Content-Type: application/json

{
    "username": "test3",
    "password" : "1234"
}

### select user
GET https://mos2022.herokuapp.com/api/v2/users?keyword=
Content-Type: application/json






### select user
GET http://localhost:8080/api/v2/users?keyword=
Content-Type: application/json

### Register user
POST http://localhost:8080/api/v2/register HTTP/1.1
Content-Type: application/json

{
    "name": "artart",
    "surname": "artart",
    "username": "art555",
    "password" : "1234"
}

### Login https://cmgostock.herokuapp.com/
POST http://localhost:8080/api/v2/login HTTP/1.1
Content-Type: application/json

{
    "username": "art555",
    "password" : "1234"
}